Replace api
openameba/passport-amebame pull request #7
Opened 2022-07-19 07:47 UTC by herablog

#4 で記述したプロフィールAPI置き換え用の変更をしました。

## 注意点
リファクタできそうな箇所もありますが、差分が見えにくくなったり想定外の動作をしてしまうかもしれず今回の対応の本筋ではないため、最小限の変更にしています。同様の理由でフォーマッタも設定していません。

## 変更内容
- モックデータを新APIに合わせました 65c80f125dcbfadf3df12211fb76058e4dc3ed89
- Strategyのコードを更新しました eb5c0a3c71e4cc68653725e4b7ced17577f2b183
- 必要なくなったリダイレクト関連のコードを消しました eb5c0a3c71e4cc68653725e4b7ced17577f2b183 
- ad5c1f5940d98bbba775687ca861b4331646ff3c

2022-07-19 09:52 UTC, takami-shunsuke approved these changes
Issueの内容と相違なく、変更問題なさそうです🙏

2022-07-20 06:23 UTC, takami-shunsuke requested changes
READMEの使い方に関しても、引数`sandbox`の変更などの反映が必要そうでした🙏

https://github.com/openameba/passport-amebame/blob/main/README.md#configure-strategy

2022-07-20 06:27 UTC, herablog commented
ありがとうございます！ドキュメント系(README, example)は最後に別PR予定です！

(まだ修正点ありますが、スタンバイ中ですｗ https://github.com/openameba/passport-amebame/commit/6e1151ac41d4a7ba3e452797badbba2c17b65ff6)

2022-07-20 06:33 UTC, takami-shunsuke approved these changes
https://github.com/openameba/passport-amebame/pull/7#issuecomment-1189880173
なるほどです、かしこまりました🙏

こちらはLGTMです！

2022-07-20 07:50 UTC, keiya01 approved these changes
良さそうです:pray:

2022-07-20 08:11 UTC, herablog commented
🙏🙏🙏🙏🙏🙏🙏🙏

2022-07-22 02:07 UTC, merged